POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker 2"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/dc3d8065-52ef-4e95-98d4-456ab1ba3b9e